// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi.Context;

#nullable disable

namespace StudentApi.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221027152855_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StudentApi.Entities.Hostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HostelName")
                        .HasColumnType("longtext");

                    b.Property<string>("HostelReg")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("StudentApi.Entities.StudentDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("CGPA")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<int?>("HostelId")
                        .HasColumnType("int");

                    b.Property<string>("HostelReg")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MatricNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TuitionFees")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TuitionFeesStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostelId");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("StudentApi.Entities.StudentDetails", b =>
                {
                    b.HasOne("StudentApi.Entities.Hostel", "Hostel")
                        .WithMany("StudentDetails")
                        .HasForeignKey("HostelId");

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("StudentApi.Entities.Hostel", b =>
                {
                    b.Navigation("StudentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
